// export const PORTFOLIOWORK = [
//     {
//         id: 0,
//         title: 'GHOST RIDER BIKES',
//         description: 'HTML CSS JS SASS SHOPIFY FIGMA ADOBE PHOTOSHOP',
//         img1: '/assets/images/graphicGhostRiderSite.png',
//         titleExample: 'GHOSTRIDER',
//         objectiveTitle: 'OBJECTIVE',
//         objective: 'To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s',
//         contributorsTitle: 'CONTRIBUTORS',
//         contributors: ['Website Development: Alicia Morley', 'Website Design: Christopher Morley', 'HTML Email Design: Alicia Morley', 'HTML Email Development: Alicia Morley'],
//         programsTitle: 'PROGRAMS & LANGUAGES',
//         programs: 'HTML, CSS, JS, SASS Preprocessor, Bootstrap, Shopify,',
//         websiteTitle: 'WEBSITE',
//         website: 'To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s',
//         siteAdressWeb: 'adressSite0',
//         siteAdressGit: 'https://github.com/Alicia-M-M',
//         siteFigma: 'https://www.figma.com/',
//         htmlEmailTitle: 'HTML EMAIL',
//         html: 'To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s',
//         emailHtmlAdress: 'adressEmailHtml0',
//         emailHtmlGit: 'https://github.com/Alicia-M-M',
//         emailHtmlFigma: 'https://www.figma.com/',
//         img2: '/assets/images/testerImage.png',
//         img3: '/assets/images/emailGhostRiderSite.png',
//         overlay: 'darkGrey',
//         font: 'white',
//     },
//     {
//         id: 1,
//         title: 'GEO PHONE PROMO SITE',
//         description: 'REACT REDUX MONGODB ATLAS EXPRESS FIGMA ADOBE PHOTOSHOP',
//         img1: '/assets/images/graphicGeoSite.png',
//         titleExample: 'GEO PHONE',
//         objectiveTitle: 'OBJECTIVE',
//         objective: 'To create an advertising site for a new brand of phonecase Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s',
//         contributorsTitle: 'CONTRIBUTORS',
//         contributors: ['Website Development: Alicia Morley', 'Website Design: Alicia Morley', 'HTML Email Design: Alicia Morley', 'HTML Email Development: Alicia Morley'],
//         programsTitle: 'PROGRAMS & LANGUAGES',
//         programs: 'React, React-Redux, CSS, JS, Reactstrap, React-Animate-on-Scroll,',
//         websiteTitle: 'WEBSITE',
//         website: 'To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s',
//         siteAdressWeb: 'adressSite1',
//         siteAdressGit: 'https://github.com/Alicia-M-M',
//         siteFigma: 'https://www.figma.com/',
//         htmlEmailTitle: 'HTML EMAIL',
//         html: 'To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s',
//         emailHtmlAdress: 'adressEmailHtml1',
//         emailHtmlGit: 'https://github.com/Alicia-M-M',
//         emailHtmlFigma: 'https://www.figma.com/',
//         img2: '/assets/images/graphicGeoSite.png',
//         img3: '/assets/images/emailGeoSite.png',
//         overlay: 'yellow',
//         font: 'black',
//     },
//     {
//         id: 2,
//         title: 'PORTFOLIO WEBSITE',
//         description: 'REACT MONGODB ATLAS EXPRESS SKETCH ADOBE PHOTOSHOP',
//         img1: '/assets/images/portfolioSite.png',
//         titleExample: 'PORTFOLIO WEBSITE',
//         objectiveTitle: 'OBJECTIVE',
//         objective: 'To create a portfolio site for me Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s',
//         contributorsTitle: 'CONTRIBUTORS',
//         contributors: ['Website Development: Alicia Morley', 'Website Design: Alicia Morley', 'HTML Email Design: Alicia Morley', 'HTML Email Development: Alicia Morley'],
//         programsTitle: 'PROGRAMS & LANGUAGES',
//         programs: 'React, Redux, Reactstrap, CSS, JS, Framer-Motion, React-Spring, React-Transition-Group',
//         websiteTitle: 'WEBSITE',
//         website: 'To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s',
//         siteAdressWeb: 'adressSite2',
//         siteAdressGit: 'https://github.com/Alicia-M-M',
//         siteFigma: 'https://www.figma.com/',
//         htmlEmailTitle: 'HTML EMAIL',
//         html: 'To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s',
//         emailHtmlAdress: 'adressEmailHtml2',
//         emailHtmlGit: 'https://github.com/Alicia-M-M',
//         emailHtmlFigma: 'https://www.figma.com/',
//         img2: '/assets/images/tester1.png',
//         img3: '/assets/images/tester2.png',
//         overlay: 'pink',
//         font: 'black',
//     },
//     {
//         id: 3,
//         title: 'WIP - JEWERY & MAKEUP',
//         description: 'HTML, CSS, JS, SKETCH, ADOBE PHOTOSHOP',
//         img1: '/assets/images/ecommerceSite.png',
//         titleExample: 'PORTFOLIO WEBSITE',
//         objectriveTitle: 'OBJECTIVE',
//         objective: 'To create an ecommerce site for jewelry and make-up Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s',
//         contibutorsTitle: 'CONTRIBUTORS',
//         contributors: ['Website Development: Alicia Morley', 'Website Design: Alicia Morley', 'HTML Email Design: Alicia Morley', 'HTML Email Development: Alicia Morley'],
//         programsTitle: 'PROGRAMS & LANGUAGES',
//         programs: 'HTML, CSS, JS, Flexbox, Wordpress',
//         websiteTitle: 'WEBSITE',
//         website: 'To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s',
//         siteAdressWeb: 'adressSite3',
//         siteAdressGit: 'https://github.com/Alicia-M-M',
//         siteFigma: 'https://www.figma.com/',
//         htmlEmailTitle: 'HTML EMAIL',
//         html: 'To create an advertising site for a new brand of bike Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. s',
//         emailHtmlAdress: 'adressEmailHtml3',
//         emailHtmlGit: 'https://www.linkedin.com/',
//         emailHtmlFigma: 'https://github.com/Alicia-M-M',
//         img2: '/assets/images/tester1.png',
//         img3: '/assets/images/tester2.png',
//         overlay: 'lightGrey',
//         font: 'white',
//     },
// ]