import { createContext } from 'react';

export const HERO = [
    {
        id: 0,
        title: 'FRONTEND DEVELOPER/DESIGNER',
        description: 'REACT   CSS   HTML   JS   REDUX   BOOTSTRAP   MONGODB   GITHUB',
        heroImage: '/assets/images/geoLandingImage.jpg'
    },
]


export const ABOUT = [

    {
        id: 0,
        intro: 'I am a front-end developer/designer who is passionate, determined and enthusiastic about coding! My journey began when I wanted to build a personal website and I didn’t have the skillset, so I set out to learn more! After the first initial steps into css, html and js I was hooked. Although coding can be challenging sometimes, I love building and working on sites, learning new languages and techniques and problem-solving to get the results needed. I’ve graduated from a full-stack coding bootcamp as well as being self taught and below is a list of languages and programs I use in my projects. In addition to coding I enjoy graphic design, walking my dog and learning languages such as French and Japanese.',
        titleFront: 'DEVELOPMENT',
        frontend: ['HTML', 'CSS', 'JS', 'REACT', 'BOOTSTRAP', 'REACTSTRAP', 'REDUX', 'MONGO DB', 'GITHUB', 'PUTS MAIL'],
        titleDesign: 'DESIGN',
        design: ['FIGMA', 'SKETCH', 'ADOBE PHOTOSHOP', 'ADOBE ILLUSTRATOR'],
        experience: 'EDUCATION & EXPERIENCE',
        experienceList: ['FULLSTACK BOOTCAMP 2020 ~- NUCAMP CALIFORNIA, USA', 'BA HONS TEXTILE DESIGN ~- CHELSEA COLLEGE OF ART, LONDON UK', '10+ DIGITAL GRAPHIC AND GRAPHIC ART ~- VARIOUS COMPANIES GLOBALLY'],
        linkedInGeneral: 'https://www.linkedin.com/in/alicia-morley-3ba99532/',
        githubGeneral: 'https://github.com/Alicia-M-M'
    }
]

export const PORTFOLIOWORK = [
    {
        id: 0,
        title: 'GHOST RIDER BIKES',
        description: 'HTML CSS JS BOOTSTRAP SASS SHOPIFY FIGMA ADOBE PHOTOSHOP',
        img1: '/assets/images/ghostRiderWebsiteFront.jpg',
        titleExample: 'GHOSTRIDER',
        objectiveTitle: 'OBJECTIVE',
        objective: 'To create a marketing & sales website and HTML email for a new brand of bike brand: ‘GhostRider’. Technology used includes HTML, SASS, Bootstrap, Shopify, Figma, Photoshop, illustrator.',
        contributorsTitle: 'CONTRIBUTORS',
        contributors: ['Website Development: Alicia Morley', 'Website Design: Third-Party UI Designer', 'HTML Email Design: Alicia Morley', 'HTML Email Development: Alicia Morley', 'Images: Unsplash, Pexels'],
        programsTitle: 'PROGRAMS & LANGUAGES',
        programs: 'HTML, CSS, JS, SASS Pre-processor, Bootstrap, Shopify',
        websiteTitle: 'WEBSITE',
        website: "For the GhostRider website my main goal was to take a figma document created by a Professional UX/UI designer and implement pixel-perfect replication using code. I heavily customized bootstrap components to re-create the UX/UI design and layout. I used sass pre-processor in order to best organize my styling utilizing variables and mixins to efficiently update mulitple areas of the site at the same time - for example the custom button and colour standards throughout. I used a gsap animation trigger on scroll to implement a rotating bike with parallax effect. For the in-site purchasing, I intergrated Shopify and edited the stylesheet to compliment the overall design of the site. Working with SASS gave me great insight into how to organise my stylesheet code in a different way to CSS. I had used SASS briefly before but this was the first time using it for so many styling elements; it was a great learning process. Collaborating with a professional designer's layout and idea really pushed me to find different ways of implementing specific design, animation and functionality, which in turn has given me a broader knowledge of the possibilities available.",
        siteAdressWeb: 'https://clever-heyrovsky-7f4df4.netlify.app',
        siteAdressGit: 'https://github.com/Alicia-M-M/ghostRiderWebsite',
        siteFigma: 'https://www.figma.com/proto/223dvFD5ATKItLVRRJHSYx/Ghost-Rider-Prototype-Doc?page-id=0%3A1&node-id=1%3A2&viewport=578%2C190%2C0.12373535335063934&scaling=min-zoom&hide-ui=1',
        htmlEmailTitle: 'HTML EMAIL',
        html: 'I designed and developed the GhostRider HTML email using the website style guide to keep the design on brand. I used Figma to design the layout and HTML for the email itself. I created buttons and graphics and added a dark mode to the email.The email is responsive, scailing where needed from a two column to a one column layout.',
        emailHtmlAdress: 'https://tender-poitras-bcb6d3.netlify.app',
        emailHtmlGit: 'https://github.com/Alicia-M-M/ghostRider-email',
        emailHtmlFigma: 'https://www.figma.com/proto/Lpbm1cRCwV3ykY2spHBXKR/html-Email-Ghost-Rider-final-render?page-id=0%3A1&node-id=20%3A2&viewport=-867%2C410%2C1&scaling=min-zoom',
        img2: '/assets/images/ghostRiderWebsite.jpg',
        img3: '/assets/images/emailGhostRiderSite.jpg',
        overlay: 'darkGrey',
        font: 'white',
    },
    {
        id: 1,
        title: 'GEO PHONE PROMO SITE',
        description: 'REACT CSS REACTSTRAP REDUX FIGMA ADOBE PHOTOSHOP',
        img1: '/assets/images/phonePromoWebsiteFront.jpg',
        titleExample: 'GEO PHONE',
        objectiveTitle: 'OBJECTIVE',
        objective: 'To design then develop a fictional promo site and HTML email for GEO PHONE. Technologies used includes React, Reactstrap, React-router, Redux, CSS Animations, Figma, Photoshop  and Illustrator.',
        contributorsTitle: 'CONTRIBUTORS',
        contributors: ['Website Development: Alicia Morley', 'Website Design: Alicia Morley', 'HTML Email Design: Alicia Morley', 'HTML Email Development: Alicia Morley', 'Images: Unsplash, Pexels'],
        programsTitle: 'PROGRAMS & LANGUAGES',
        programs: 'React, React-Redux, CSS, Reactstrap, React-Animate-on-Scroll,',
        websiteTitle: 'WEBSITE',
        website: 'I developed the site to have multiple re-useable components using react and also to use react hooks such as useState to add state to my functional components and useEffect to mange any ‘side-effects’ in my components. For navigation I used react-router and react-router-hash-link and for updating and managing state I used redux. I used conditional statements, ternary operators and CSS to implement different visual results depending on criteria. My site is currently a "work in progress" as I am in the process of implementing a data-base hosted on mongo db Atlas and intergrating a backend into the project using express, cors and mongoose. Designing the site and using the Figma layout as a guideline really challenged me to get the end result exactly like the initial concept.',
        emailHtmlAdress: 'https://kind-stonebraker-b436ef.netlify.app',
        siteAdressWeb: 'https://friendly-poincare-114884.netlify.app',
        siteAdressGit: 'https://github.com/Alicia-M-M/geo-phone-website',
        siteFigma: 'https://www.figma.com/proto/iCqR5r5kYcQrB8FxaaJI5P/Phone-Promo-React-app-render-final?page-id=0%3A1&node-id=1%3A2&viewport=-4191%2C2051%2C0.5&scaling=min-zoom',
        htmlEmailTitle: 'HTML EMAIL',
        html: 'I developed the ‘GEO PHONE’ html email adding an animated gif to the header which created in photoshop. I used Figma to design the layout and HTML for the email itself. I created png buttons and graphics in Photoshop and added a dark mode to the email.',
        emailHtmlGit: 'https://github.com/Alicia-M-M/geo-phone-email',
        emailHtmlFigma: 'https://www.figma.com/proto/1gVErmZbDUY9vX1Wwoklmw/phone-promo-html-email-final-render?page-id=0%3A1&node-id=1%3A2&viewport=-1932%2C912%2C4&scaling=min-zoom',
        img2: '/assets/images/phonePromoWebsite.jpg',
        img3: '/assets/images/emailGeoSiteV1.jpg',
        overlay: 'yellow',
        font: 'black',
    },
    {
        id: 2,
        title: 'PORTFOLIO WEBSITE',
        description: 'REACT REACTSTRAP SKETCH ADOBE PHOTOSHOP ADOBE ILLUSTRATOR',
        img1: '/assets/images/portfolioWebsiteFront.jpg',
        titleExample: 'PORTFOLIO WEBSITE',
        objectiveTitle: 'OBJECTIVE',
        objective: 'To design then develop my personal portfolio and HTML email. To build the site I used React, Reactstrap, userContext, react-router, Framer-Motion, react-spring, Sketch, photoshop and illustrator.',
        contributorsTitle: 'CONTRIBUTORS',
        contributors: ['Website Development: Alicia Morley', 'Website Design: Alicia Morley', 'HTML Email Design: Alicia Morley', 'HTML Email Development: Alicia Morley', 'Images: Unsplash, Pexels'],
        programsTitle: 'PROGRAMS & LANGUAGES',
        programs: 'React, Redux, Reactstrap, CSS, JS, Framer-Motion, React-Spring, React-Transition-Group',
        websiteTitle: 'WEBSITE',
        website: 'For my portfolio site I really wanted to have a simple design with some elegant functionality, styling and animations. I really enjoyed creating the intro ‘alicia morley’ signature using css animations and svg paths. I used userContext as a way to pass my data throughout my application without prop drilling. I implemented useMediaQuery from react-responsive with css variables for the dark mode functionality and stored the users preference in localStorage so on page change/navigating away from the page the preference is temporarily stored. For the on click navigation to view the portfolio items react-router params has been used.',
        siteAdressWeb: 'adressSite2',
        siteAdressGit: 'https://github.com/Alicia-M-M',
        siteFigma: 'https://www.sketch.com/s/12b337fb-6fb4-4a43-9726-2fe54b94e452/a/dlWoW5n/play',
        htmlEmailTitle: 'HTML EMAIL',
        html: 'I developed my Portfolio HTML email keeping everything simple and on brand with my website so when it is emailed to recruiters and companies all my information and experience is clear. I used Sketch to design the layout and HTML for the email itself. I created png buttons and graphics and added a dark mode.',
        emailHtmlAdress: 'https://jovial-pike-edbf80.netlify.app',
        emailHtmlGit: 'https://github.com/Alicia-M-M/portfolio-email',
        emailHtmlFigma: 'https://www.sketch.com/s/80975f55-09a4-441c-a10a-2d3298cb8de3',
        img2: '/assets/images/portfolioWebsite.jpg',
        img3: '/assets/images/portfolioEmail.jpg',
        overlay: 'pink',
        font: 'black',
    },
    {
        id: 3,
        title: 'LUXURY PRODUCT SITE',
        description: 'HTML CSS JAVASCRIPT SKETCH ADOBE PHOTOSHOP',
        img1: '/assets/images/luxuryFrontCover.jpg',
        titleExample: 'PORTFOLIO WEBSITE',
        objectiveTitle: 'OBJECTIVE',
        objective: 'To design then develop an eccomerce page with search, sort and wishlist functionality. Technologies used include HTML, CSS, JS, flex-box, Sketch and Photoshop.',
        contributorsTitle: 'CONTRIBUTORS',
        contributors: ['Website Development: Alicia Morley', 'Website Design: Alicia Morley', 'HTML Email Design: Alicia Morley', 'HTML Email Development: Alicia Morley', 'Images: Unsplashed, Pexels'],
        programsTitle: 'PROGRAMS & LANGUAGES',
        programs: 'HTML, CSS, JS, Flexbox',
        websiteTitle: 'WEBSITE',
        website: "For the Luxury site I wanted to create all the functional components with JavaScript. I built a product grid layout that on click would add an item to a wishList. I also added a fixed sidebar for the product filters and a keyword search bar for more specific filtering of products. I used flex-box for layout and scaleability at specific breakpoints. I wanted to keep the page styling very clean and simple using high impact images from Pexels and Unsplash for a luxury ecommerce feel. The project is still a 'WIP' as I would like to add futher funtional elements to the site aswell as some subtle on hover animations for the images and texts. I would also like to amend a problem I had with my build files. I am using an npm package called 'usemin' and it is not very compatable with ES6 so I had to change my 'let's to 'var's otherwise the run build would exit with a build error. After research I've found a replacement for uglify.js - Terser, and I will update my build at a later stage.",
        siteAdressWeb: 'https://vibrant-swanson-9fe6e9.netlify.app/',
        siteAdressGit: 'https://github.com/Alicia-M-M/luxuryWebsite',
        siteFigma: 'https://www.figma.com/proto/2VMu6pTsuhLT41mjZ293g5/luxuryWebsite-Final?page-id=0%3A1&node-id=118%3A121&viewport=80%2C370%2C0.21917660534381866&scaling=min-zoom',
        htmlEmailTitle: 'HTML EMAIL',
        html: 'I developed the Luxury HTML email making sure that the images when scaled to a small screen size would still look great as I wanted the imagery to be full page on all sizes/not break into smaller columns as on previous designs. When designing the layout I thought this would look really impactful and dynamic like alot of current retail emails. I kept all the styling on brand by designing the layout in Figma.I also create an animated header giff that continuously rotates',
        emailHtmlAdress: 'https://clever-franklin-7b245e.netlify.app',
        emailHtmlGit: 'https://github.com/Alicia-M-M/luxury-email/',
        emailHtmlFigma: 'https://www.figma.com/proto/d3ivTf69hhOKpZNIWXjysq/luxuryHtmlEmail-Final?page-id=0%3A1&node-id=10%3A113&viewport=-793%2C290%2C0.6674285531044006&scaling=min-zoom',
        img2: '/assets/images/luxuryImagePortfolio.jpg',
        img3: '/assets/images/luxuryEmail.jpg',
        overlay: 'lightGrey',
        font: 'white',
    },
]



export const UserContext = createContext([HERO, ABOUT, PORTFOLIOWORK])